### ISSUE TITLE
RuntimeError: Unknown model (resnet50_cifar100)

### ISSUE THREAD

**Issue by ufestkc** [metastacy/mobilenet_cifar100_kd#1]
"t_network = timm.create_model("resnet50_cifar100", pretrained=True)" RuntimeError: Unknown model (resnet50_cifar100)
it seems like there is no resnet50_cifar100 ?

**Comment by metastacy** [comment]
hey @ufestkc, the problem should be fixed now; just needed to import the "dectectors" library so the timm model could be imported correctly.

**Comment by niruem** [comment]
hey @ufestkc, the problem should be fixed now; just needed to import the "dectectors" library so the timm model could be imported correctly.
