### ISSUE TITLE
is there any change?

### ISSUE THREAD

**Issue by ufestkc** [metastacy/mobilenet_cifar100_kd#2]
First, thank u for responding me for the last issue, and I run your code successfully 
and the result is amazing 74%, though I changed something in your code, like the optimizer and lr schedule, which is following this: https://github.com/megvii-research/mdistiller/blob/master/configs/cifar100/dkd/res50_mv2.yaml . 
Given that in the DKD paper, the reported accuracy is only 70.35%, so the 74% is definitely amazing. 
**I was wondering if you changed somewhere based on the original DKD code?**
I really couldn't understand their code, but yours is very clear, thanks to you.

**Comment by metastacy** [comment]
74% is really good! As for any changes, I do not recall doing anything significant. I only did two modifications: one of the arguments of the foward_train() function of the DKD class was changed from "**kwargs" to "epoch", and the other was substituting the other instance `kwargs["epoch"]` to just "epoch".  For reference, in the DKD_ResNet50toMobileNetV2.py file, the first modification was on line 251, and the second on line 258.

I appreciate your comment!

**Comment by niruem** [comment]
@ufestkc, 74% is really good! As for any changes, I do not recall doing anything significant. I only did two modifications: one of the arguments of the foward_train() function of the DKD class was changed from "**kwargs" to "epoch", and the other was substituting the other instance kwargs["epoch"] to just "epoch". For reference, in the DKD_ResNet50toMobileNetV2.py file, the first modification was on line 251, and the second on line 258.

I appreciate your comment!

**Comment by ufestkc** [comment]
> @ufestkc, 74% is really good! As for any changes, I do not recall doing anything significant. I only did two modifications: one of the arguments of the foward_train() function of the DKD class was changed from "**kwargs" to "epoch", and the other was substituting the other instance kwargs["epoch"] to just "epoch". For reference, in the DKD_ResNet50toMobileNetV2.py file, the first modification was on line 251, and the second on line 258.
> 
> I appreciate your comment!

Thanks for your explanation. I have to say it again, this is just amazing!

**Comment by ufestkc** [comment]
hi, today I noticed that your mobilenet v2 differs from the original author's (https://github.com/megvii-research/mdistiller/blob/master/mdistiller/models/cifar/mobilenetv2.py), which leads to different results(yours 74%, his 67%). Why is that? Where did your mobilenet code come from? I am confused lol

**Comment by niruem** [comment]
@ufestkc Yes, I got the code from another repo. As to what repo, I could not tell. I assume the MobileNetV2 I used is more complex. I completely forgot to mention that, apologies.

**Comment by ufestkc** [comment]
> @ufestkc Yes, I got the code from another repo. As to what repo, I could not tell. I assume the MobileNetV2 I used is more complex. I completely forgot to mention that, apologies.

that's ok, thank u anyway
